# Generated by Django 5.1.4 on 2025-08-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Grocery', 'Grocery'), ('Essential', 'Essential')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
