# Generated by Django 5.1.4 on 2025-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode or QR code value (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Grocery', 'Grocery'), ('Household', 'Household'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
