# Generated by Django 5.1.4 on 2025-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_item_barcode_item_notes_alter_item_added_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=199)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
