# Generated by Django 4.2 on 2025-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='donated',
            field=models.BooleanField(default=False, help_text='Mark if item has been donated'),
        ),
    ]
