# Generated by Django 4.2 on 2025-10-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('categories_accepted', models.CharField(choices=[('Medicine', 'Medicine'), ('Grocery', 'Grocery'), ('Household', 'Household')], default='Medicine', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='NGO verification status')),
                ('verification_badge', models.CharField(blank=True, help_text="Verification badge text (e.g., 'Government Verified')", max_length=50, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Rating out of 5 stars', max_digits=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, help_text='e.g., Mon-Fri 9AM-5PM', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
            },
        ),
    ]
