# Generated by Django 4.2 on 2025-11-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_ngo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NGO',
        ),
    ]
