# Generated by Django 4.2 on 2025-12-18 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0009_delete_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Enable push notifications for expiring items'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', unique=True)),
                ('p256dh', models.CharField(help_text='P-256 elliptic curve Diffie-Hellman public key', max_length=88)),
                ('auth', models.CharField(help_text='Authentication secret', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
