# Generated by Django 4.2 on 2025-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_userprofile_push_reminders_enabled_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminder_days',
            field=models.PositiveIntegerField(default=7, help_text='Days before expiry to send reminders (1-30)'),
        ),
    ]
