# Generated by Django 6.0 on 2025-12-20 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_userprofile_reminder_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO')], default='donor', max_length=10),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo', models.CharField(help_text='NGO organization name', max_length=200)),
                ('ngo_email', models.EmailField(help_text='NGO contact email', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_address', models.TextField(help_text='Address for pickup')),
                ('contact_number', models.CharField(help_text='Donor contact number', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Full name of the NGO organization', max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='NGO registration number', max_length=100, null=True)),
                ('contact_person', models.CharField(help_text='Primary contact person', max_length=100)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('address', models.TextField(help_text='Complete address of the NGO')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, help_text='NGO website URL', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of NGO activities', null=True)),
                ('verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGOInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the medicine/item', max_length=100)),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Grocery', 'Grocery'), ('Household', 'Household'), ('Others', 'Others')], default='Medicine', max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Barcode if available', max_length=100, null=True)),
                ('expiry_date', models.DateField(help_text='Expiry date of the medicine')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity received')),
                ('batch_number', models.CharField(blank=True, help_text='Batch number', max_length=100, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('source_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_inventory', to='tracker.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tracker.ngoprofile')),
            ],
        ),
    ]
