# Generated by Django 6.0 on 2025-12-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_userprofile_user_type_donation_ngoprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='ngo_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='tracker.ngoprofile'),
        ),
    ]
